<?php

namespace LouvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
    public function getCommandeWithTicketAndPrice($id) {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->innerJoin('a.tickets','c')
            ->addSelect('c');
        $qb
            ->innerJoin('c.price','d')
            ->addSelect('d');
        $qb
            ->where('a.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

    public function getDaysOverLimitTickets($limit) {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->select('a.date')
            ->innerJoin('a.tickets', 'c')
            ->groupBy('a.date')
            ->having('COUNT(a) > :count AND a.date > :now')
            ->setParameter('count', $limit)
            ->setParameter('now', new \DateTime('yesterday'));
        return $qb->getQuery()->getResult();
        }
}
//SELECT COUNT(*) FROM commande INNER JOIN ticket on commande.id = ticket.commande_id GROUP BY date HAVING COUNT(*) > 1 AND DATE > NOW()
